// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://earvjqvafjivvgrfeqxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhcnZqcXZhZmppdnZncmZlcXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTMzOTgsImV4cCI6MjA2MTk2OTM5OH0.o4aeZQAOC85ZVIJDwBcROdMhQN1UMaI7P374EBhXdPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);